name : Cache Node and NPM dependencies
description: Caches Node.js and NPM dependencies to speed up workflow runs


inputs:
   node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
   working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
   target-env :
     description : '"dev" or  "prod".  Controlls whether dev dependencies are installed.'
     required: false
     default: "dev"


runs:
  using: composite
  steps:
    - name: Setup Node.js version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: deps-node-modules-${{inputs.target-env}}--${{ hashFiles(format('{0}/{1}', inputs.working-directory, 'package-lock.json')) }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

      