name: 06 - Contexts
run-name: 06 - Context | DEBUG - ${{inputs.debug}}

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env:
    MY_WORKFLOW_ENV: "workflow level"
    MY_OVERWRITTEN_ENV: "OVERWRITTEN workflow level"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_ENV: "job level"
            MY_OVERWRITTEN_ENV: "OVERWRITTEN job level"
        steps:
            - name: Display information
              env:
                  MY_STEP_ENV: "step level"
                  MY_OVERWRITTEN_ENV: "OVERWRITTEN step - 1 level"
              run: |
                  echo "Event Name: ${{github.event_name}}"
                  echo "Ref: ${{github.ref}}"
                  echo "SHA: ${{github.sha}}"
                  echo "Actor: ${{github.actor}}"
                  echo "Workflow: ${{github.workflow}}"
                  echo "Run ID: ${{github.run_id}}"
                  echo "Run number: ${{github.run_number}}"

            - name: Retrieve Variable
              run: |
                  echo "Variable value: ${{vars.MY_VAR}}"

            - name: Display Env
              env:
                  MY_OVERWRITTEN_ENV: "OVERWRITTEN step - 3 level"
              run: |
                  echo "workflow env: $MY_WORKFLOW_ENV"
                  echo "job env: $MY_JOB_ENV"
                  echo  "step env: $MY_STEP_ENV"
                  echo "overwritten env: ${{env.MY_OVERWRITTEN_ENV}}"
                  echo "overwritten env: $MY_OVERWRITTEN_ENV"
