name: 08 - Using env
run-name: USING ENV

on:
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "I am a workflow env var"
    OVERWRITTEN: "I WIL BE OVERWRITTEN"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env var"
            OVERWRITTEN: "I have been overwritten at the job level"
        steps:
            - name: Print ENV variables
              env:
                  STEP_VAR: "I am a step var"
                  step_var2: "I am another step env var"
              run: |
                  echo "Step env var: ${{env.STEP_VAR}}"
                  echo "Step env var 2: $step_var2"
                  echo "Job env var: ${{env.JOB_VAR}}"
                  echo "Workflow env var: $WORKFLOW_VAR"
                  echo "OVERWRITTEN: ${{env.OVERWRITTEN}}"

            - name: Overwritten JOB variable
              env:
                  OVERWRITTEN: "I have been overwritten at the stop level"
              run: |
                  echo "step one env: Step env var $STEP_VAR"
                  echo "step two env: ${{env.OVERWRITTEN}}"
