name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: "Skip deployment and only print build output"
                type: boolean
                default: false

            target:
                type: environment
                required: true
                description: "Which environment the workflow will target"

            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: "Release from which to build and deploy"

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo "Building from tag ${{ inputs.tag }}"

    deploy:
        runs-on: ubuntu-latest
        if: ${{ inputs.dry-run == 'false' }}
        environment: ${{ inputs.target }}
        steps:
            - name: deploy
              run: echo "Deploy to ${{ inputs.target }}"
