name: 14 - Working with Artifacts

on:
    workflow_dispatch:

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-app

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Download cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: 14-artifact/react-app/node_modules
                  key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Unit tests
              run: npm run test

            - name: Build
              run: npm run build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: react-app-build
                  path: 14-artifacts/react-app/build

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: react-app-build
                  path: ./downloaded-artifacts

            - name: Show folder structure
              run: ls -R
