name: 15 - Working with  matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os}} - Node.js ${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                      tag: experimental

        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: perform some tests
              run: |
                  echo "Running tests on OS ${{matrix.os}} and Nodejs ${{matrix.node-version}}"

            - name: upload results
              run: |
                  echo  "Uploading results for OS ${{matrix.os}} and Nodejs ${{matrix.node-version}}"

    include-example:
        name: ${{ matrix.color}} - ${{ matrix.shape }} - ${{matrix.size}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                size: [small, large]
                shape: [circle, square]
                include:
                    - color: red
                      opacity: 1.0
                    - shape: circle
                      opacity: 0.75
                    - color: red
                      shape: triangle
                    - opacity: 0.5

                exclude:
                    - color: green
                      shape: triangle
                    - size: large
                      shape: triangle
                    - color: green
                      size: large
                      shape: square

        steps:
            - name: show values
              run: |
                  echo "Color is ${{matrix.color}}"
                  echo "Size is ${{matrix.size}}"
                  echo "Shape is ${{matrix.shape}}"
                  echo "Opacity is ${{matrix.opacity}}"
