name: 17 - Custom Actions - Composite

on:
    workflow_dispatch:
env:
    working-directory: 17-custom-actions/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js and dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with:
                  node-version: "20.x"
                  working-directory: ${{ env.working-directory }}

            - name: "Test"
              run: npm run test

            - name: Build
              run: npm run build
